/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ClienteController;

/**
 *
 * @author Raparthur
 */
public class BotoesCliente extends javax.swing.JPanel {

    /**
     * Creates new form BotoesCliente
     */
    public BotoesCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisarClientesTxt = new javax.swing.JTextField();
        pesquisarClientesBtn = new javax.swing.JButton();
        inserirClienteBtn = new javax.swing.JButton();
        listarClientesBtn = new javax.swing.JButton();
        atualizarClienteBtn = new javax.swing.JButton();
        excluirClienteBtn = new javax.swing.JButton();

        pesquisarClientesBtn.setText("Pesq");

        inserirClienteBtn.setText("Inserir");

        listarClientesBtn.setText("Listar");

        atualizarClienteBtn.setText("Atualizar");

        excluirClienteBtn.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesquisarClientesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarClientesBtn)
                .addGap(83, 83, 83)
                .addComponent(inserirClienteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listarClientesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarClienteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirClienteBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarClientesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarClientesBtn)
                    .addComponent(inserirClienteBtn)
                    .addComponent(listarClientesBtn)
                    .addComponent(atualizarClienteBtn)
                    .addComponent(excluirClienteBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarClienteBtn;
    private javax.swing.JButton excluirClienteBtn;
    private javax.swing.JButton inserirClienteBtn;
    private javax.swing.JButton listarClientesBtn;
    private javax.swing.JButton pesquisarClientesBtn;
    private javax.swing.JTextField pesquisarClientesTxt;
    // End of variables declaration//GEN-END:variables

    void setController(ClienteController controller) {
        this.inserirClienteBtn.addActionListener(e -> controller.inserirCliente());
        this.atualizarClienteBtn.addActionListener(e -> controller.atualizarCliente());
        this.listarClientesBtn.addActionListener(e -> controller.listarTodosClientes());
        this.excluirClienteBtn.addActionListener(e -> controller.excluirClientes());
        this.pesquisarClientesBtn.addActionListener(e -> controller.pesquisarClientes(pesquisarClientesTxt.getText()));
    }

}
