/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.PedidoController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.util.ArrayList;
import java.util.List;
import model.Cliente;

/**
 *
 * @author Raparthur
 */
public class FormularioClientePedidos extends javax.swing.JPanel {

    private List<Cliente> clienteList = new ArrayList<>();
    private Cliente clienteSelec;

    /**
     * Creates new form FormularioPedidos
     */
    public FormularioClientePedidos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clientePedidoCbbox = new javax.swing.JComboBox<>();
        filtroClienteTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        okClienteBtn = new javax.swing.JButton();
        filtrarClienteBtn = new javax.swing.JButton();

        jLabel1.setText("cliente");

        jLabel2.setText("filtro");

        okClienteBtn.setText("ok");

        filtrarClienteBtn.setText("filtrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addComponent(filtroClienteTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtrarClienteBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clientePedidoCbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okClienteBtn))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientePedidoCbbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okClienteBtn)
                    .addComponent(filtrarClienteBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> clientePedidoCbbox;
    private javax.swing.JButton filtrarClienteBtn;
    private javax.swing.JTextField filtroClienteTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okClienteBtn;
    // End of variables declaration//GEN-END:variables

    public void setClienteList(List<Cliente> clientes) {
        clienteList = clientes;
        clientePedidoCbbox.removeAllItems();
        for (Cliente cliente : clientes) {
            clientePedidoCbbox.addItem(cliente.getNome());
        }
    }
    
    public Cliente getClienteSelecionado(){
        if(clienteList.isEmpty() || clientePedidoCbbox.getSelectedIndex() == -1){
            return null;
        }
        return this.clienteSelec;
    }

    public void setController(PedidoController controller) {
 
        //busca pedidos do cliente selecionado
        this.okClienteBtn.addActionListener(e -> {
            for(int i=0;i<clienteList.size();i++){
                if(clientePedidoCbbox.getSelectedIndex() == i){
                    this.clienteSelec = clienteList.get(i);
                     controller.listaPedidosCliente(this.clienteSelec);
                }
            }
        });
        
        //filtra clientes e (re)preenche a lista baseado no termo
        this.filtrarClienteBtn.addActionListener(e -> {
            controller.filtraClientes(filtroClienteTxt.getText());
        });
    }

}
