/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.PedidoController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import model.Pedido;
import model.Pizza;

/**
 *
 * @author Raparthur
 */
public class FormularioPedidos extends javax.swing.JPanel {

    private PedidoController controller;
    private List<Pedido> pedidossList = new ArrayList<>();
    private BigDecimal totalPedido = new BigDecimal(0.0);

    /**
     * Creates new form FormularioPizzaPedidos
     */
    public FormularioPedidos() {
        initComponents();
        pedidoCbbox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Pedido pedido = getPedidoSelecionado();
                if (pedido != null) {
                    for (int i = 0; i < pedidossList.size(); i++) {
                        if (pedido.getId() == pedidossList.get(i).getId()) {
                            estadoCbbox.setSelectedIndex(pedidossList.get(i).getEstado());
                        }
                    }
                    controller.setPedidoSelecionado(pedido);
                }
            }
        });
        
        alterEstBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Pedido pedido = getPedidoSelecionado();
                if (pedido != null) {
                    for (int i = 0; i < pedidossList.size(); i++) {
                        if (pedido.getId() == pedidossList.get(i).getId()) {
                            pedidossList.get(i).setEstado(estadoCbbox.getSelectedIndex());
                            controller.alterarEstado(pedidossList.get(i));
                            break;
                        }
                    }

                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estadoCbbox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pedidoCbbox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        clienteLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalPedidiLbl = new javax.swing.JLabel();
        alterEstBtn = new javax.swing.JButton();

        jLabel4.setText("estado");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("CLIENTE:");

        clienteLbl.setText("---------");

        jLabel7.setText("ID PEDIDO");

        jLabel1.setText("total");

        totalPedidiLbl.setText("0.00");

        alterEstBtn.setText("alterar ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(clienteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pedidoCbbox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estadoCbbox, 0, 100, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alterEstBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPedidiLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clienteLbl)
                            .addComponent(pedidoCbbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadoCbbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alterEstBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPedidiLbl)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterEstBtn;
    private javax.swing.JLabel clienteLbl;
    private javax.swing.JComboBox<String> estadoCbbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> pedidoCbbox;
    private javax.swing.JLabel totalPedidiLbl;
    // End of variables declaration//GEN-END:variables

    
    public void setPedidoDoCliente(List<Pedido> pedidos) {
        pedidossList = pedidos;
        if (pedidos.isEmpty()) {
            return;
        }

        pedidoCbbox.removeAllItems();
        estadoCbbox.removeAllItems();
        estadoCbbox.addItem(Pedido.ESTADO_ABERTO); //0
        estadoCbbox.addItem(Pedido.ESTADO_A_CAMINHO); //1
        estadoCbbox.addItem(Pedido.ESTADO_ENTREGUE); //2

        for (Pedido pedido : pedidossList) {
            pedidoCbbox.addItem("#" + pedido.getId());
        }

        estadoCbbox.setSelectedIndex(pedidossList.get(0).getEstado());
        clienteLbl.setText(pedidossList.get(0).getCliente().getNome() + " " + pedidossList.get(0).getCliente().getSobrenome());

    }

    public Pedido getPedidoSelecionado() {
        for (int i = 0; i < pedidossList.size(); i++) {
            if (pedidoCbbox.getSelectedIndex() == i) {
                setTotalPedido(pedidossList.get(i).getPizzas());
                return pedidossList.get(i);
            }
        }
        return null;
    }
    
    public void setPedidoSelecionado(Pedido pedido){
        for (int i = 0; i < pedidossList.size(); i++) {
            if(pedidossList.get(i).getId() == pedido.getId()){
                pedidoCbbox.setSelectedIndex(i);
            }
        }
    }
    
    public List<Pedido> getPedidosCliente(){
        return this.pedidossList;
    }

    void setController(PedidoController controller) {
        this.controller = controller;
    }

    public void setTotalPedido(List<Pizza> pizzas) {
        BigDecimal total = new BigDecimal(0.0);
        for (Pizza pizza : pizzas) {
            total = total.add(new BigDecimal(pizza.getValor()));
        }
        this.totalPedido = total.setScale(2, RoundingMode.HALF_DOWN);
        totalPedidiLbl.setText(String.valueOf(this.totalPedido));
    }

    public void adiconaTotalPedido(Pizza pizza) {
        this.totalPedido = this.totalPedido.add(new BigDecimal(pizza.getValor()));
        this.totalPedido = this.totalPedido.setScale(2, RoundingMode.HALF_DOWN);
        this.totalPedidiLbl.setText(String.valueOf(this.totalPedido));
    }
}
