/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.Cliente;

/**
 *
 * @author Raparthur
 */
public class FormularioCliente extends javax.swing.JPanel {
    
    private Cliente clienteSelecionadoParaAtualizacao;

    /**
     * Creates new form FormularioCliente
     */
    public FormularioCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeClienteTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sobrenomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        telCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("nome");

        jLabel2.setText("sobrenome");

        jLabel3.setText("tel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 196, Short.MAX_VALUE))
                    .addComponent(nomeClienteTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sobrenomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(telCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobrenomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nomeClienteTxt;
    private javax.swing.JTextField sobrenomeCliente;
    private javax.swing.JTextField telCliente;
    // End of variables declaration//GEN-END:variables


    Cliente getFormularioPreenchido(){
        String nome = nomeClienteTxt.getText();
        String sobrenome = sobrenomeCliente.getText();
        String tel = telCliente.getText();
        
        
        if(nome.isBlank() || sobrenome.isBlank() || tel.isBlank()){
            return null;
        }
        
        Cliente c = new Cliente();
        c.setId(0);
        c.setNome(nome);
        c.setSobrenome(sobrenome);
        c.setTel(tel);
        return c;
    }
    
    public void setClienteParaPreencher(Cliente cliente) {
        this.clienteSelecionadoParaAtualizacao = cliente;
        nomeClienteTxt.setText(cliente.getNome());
        sobrenomeCliente.setText(cliente.getSobrenome());
        telCliente.setText(cliente.getTel()); 
    }

    public Cliente getClienteParaAtualizar() {
        if(this.clienteSelecionadoParaAtualizacao==null){
            return null;
        }
        this.clienteSelecionadoParaAtualizacao.setNome(nomeClienteTxt.getText());
        this.clienteSelecionadoParaAtualizacao.setSobrenome(sobrenomeCliente.getText());
        this.clienteSelecionadoParaAtualizacao.setTel(telCliente.getText());
        return this.clienteSelecionadoParaAtualizacao;
                
    }
}
